name: SLSA Source Provenance Creator

description: Creates SLSA Source Track Provenance

runs:
  using: "Composite"
  steps:
    # This PoC depends on creating and checking information when branches are updated (e.g. via push).
    # Don't allow runs that do not occur during pushes.
    - id: check_push
      if: ${{ github.event_name != 'push' }}
      run: |
        echo "This action can only be run during a push."
        exit 1
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache-dependency-path: |
          sourcetool/go.sum
    - id: setup
      run: mkdir -p metadata
      shell: bash
    - id: handle_branch_push
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      run: |
        echo "## SLSA Source Properties Branch Push" >> $GITHUB_STEP_SUMMARY
        go run github.com/slsa-framework/slsa-source-poc/sourcetool@8bd18b3c28cdbf13162ad25534eaf84cf3b61694 --github_token ${{ github.token }} checklevelprov --commit ${{ github.sha }} --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }} --branch ${{ github.ref_name }} --output_signed_bundle ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl >> $GITHUB_STEP_SUMMARY
      shell: bash
    - id: handle_tag_push
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        echo "## SLSA Source Properties Tag Push" >> $GITHUB_STEP_SUMMARY
        go run github.com/slsa-framework/slsa-source-poc/sourcetool@8bd18b3c28cdbf13162ad25534eaf84cf3b61694 --github_token ${{ github.token }} checktag --commit ${{ github.sha }} --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }} --tag_name ${{ github.ref_name }} --actor ${{github.triggering_actor}} --output_signed_bundle ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl >> $GITHUB_STEP_SUMMARY
      shell: bash
    - id: summary
      run: |
        echo "## Signed Bundle" >> $GITHUB_STEP_SUMMARY
        cat ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl >> $GITHUB_STEP_SUMMARY
      shell: bash
    - uses: slsa-framework/slsa-source-poc/actions/store_note@main
      with:
        path: ${{ github.workspace }}/metadata/signed_bundle.intoto.jsonl
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: prov_metadata
        path: ./metadata/
